const { chromium } = require(process.env.PW);
// click a battle action by matching its label, looked up fresh inside the page each time
async function tapAction(p, re) {
  return await p.evaluate(src => {
    const rx = new RegExp(src);
    const b = [...document.querySelectorAll('#tActs button')].find(x => rx.test(x.textContent) && !x.disabled);
    if (!b) return false; b.click(); return true;
  }, re.source);
}

const problems = [], steps = [];
(async () => {
  const b = await chromium.launch(); const c = await b.newContext({ viewport: { width: 390, height: 844 } }); const p = await c.newPage();
  p.on('pageerror', e => problems.push('JS ERROR: ' + e.message));
  p.on('console', m => { if (m.type() === 'error' && !/net::|ERR_|Failed to load|favicon/.test(m.text())) problems.push('CONSOLE: ' + m.text().slice(0, 120)); });
  p.on('dialog', d => d.accept());
  await p.addInitScript(() => { try { localStorage.setItem('scouter-intro','1'); localStorage.setItem('scouter-version','107'); localStorage.setItem('scouter-a2hs','1'); } catch(e){}
    window.__said = []; try { Object.defineProperty(window, 'speechSynthesis', { configurable: true, get: () => ({ speak: u => window.__said.push(u.text), cancel: () => {} }) }); } catch (e) {}
    window.SpeechSynthesisUtterance = function (t) { this.text = t; };
    try { Object.defineProperty(navigator, 'wakeLock', { configurable: true, get: () => ({ request: async () => ({ release: async () => {}, addEventListener: () => {} }) }) }); } catch (e) {} });
  await p.route('https://overpass-api.de/**', r => r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ elements: [ { type:'node', id:1, lat:43.4520, lon:-80.4930, tags:{ name:'Victoria Park Clock Tower', historic:'monument' } }, { type:'node', id:3, lat:43.4508, lon:-80.4936, tags:{ name:'Kitchener City Hall', amenity:'townhall' } }, { type:'node', id:4, lat:43.4531, lon:-80.4902, tags:{ name:'THEMUSEUM', tourism:'museum' } } ] }) }));
  await p.route('https://tile.openstreetmap.org/**', r => r.fulfill({ status: 200, contentType: 'image/png', body: Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d4944415478da63fcffff3f0300050001a5f645bd0000000049454e44ae426082','hex') }));
  await p.route('https://routing.openstreetmap.de/**', r => { const seg = r.request().url().split('/route/v1/')[1].split('?')[0].split('/')[1]; const [a,z]=seg.split(';').map(x=>x.split(',').map(Number)); const from=[a[1],a[0]],to=[z[1],z[0]],mid=[to[0],from[1]];
    r.fulfill({ status:200, contentType:'application/json', body: JSON.stringify({ routes:[{ distance:1200, duration:900, geometry:{type:'LineString',coordinates:[[from[1],from[0]],[mid[1],mid[0]],[to[1],to[0]]]}, legs:[{steps:[{distance:700,name:'Water Street',maneuver:{type:'depart',modifier:'north',location:[from[1],from[0]]}},{distance:500,name:'Borden Avenue',maneuver:{type:'turn',modifier:'right',location:[mid[1],mid[0]]}},{distance:0,name:'',maneuver:{type:'arrive',location:[to[1],to[0]]}}]}] }] }) }); });
  await p.route('https://nominatim.openstreetmap.org/**', r => r.fulfill({ status:200, contentType:'application/json', body: JSON.stringify([{ place_id:1, display_name:'Kitchener Market, 300, King Street East, Kitchener', lat:'43.4519', lon:'-80.4869' }]) }));
  const cloud = {};
  await p.route('https://iahddcqeeqdrdrxjyhvi.supabase.co/rest/v1/rpc/**', r => { const fn = r.request().url().split('/rpc/')[1]; const a = r.request().postDataJSON();
    const R = { wp_register:{id:'p1',token:'t1',friend_code:'ABCD1234'}, wp_touch:{ok:true,friend_code:'ABCD1234'}, wp_leaderboard:[{handle:'Sobia',value:9}], wp_friends:[], wp_my_trades:[], wp_nearby_ghosts:[], wp_friend_ghosts:[], wp_recent_ghosts:[], wp_cloud_stamp:{ok:false}, wp_cloud_load:{ok:false}, wp_cloud_save:{ok:true,updated_at:new Date().toISOString(),bytes:10}, wp_region_week:{ok:true,seed:7,freed:[],admin_by:null,boss_by:null}, wp_add_friend:{ok:true,handle:'Sobia'}, wp_link_start:{ok:true,code:'AB12CD',minutes:15} }[fn];
    r.fulfill({ status:200, contentType:'application/json', body: JSON.stringify(R === undefined ? true : R) }); });
  const step = async (name, fn) => { const before = problems.length; try { await fn(); } catch (e) { problems.push('STEP FAILED (' + name + '): ' + e.message.split('\n')[0].slice(0, 110)); } steps.push(name + (problems.length > before ? '  ← problem' : '')); };

  await p.goto('http://localhost:8765/v107-localleaflet.html'); await p.waitForTimeout(1200);
  await step('load pack', async () => { await p.setInputFiles('#packBin', 'pack.bin'); await p.waitForFunction(() => document.querySelectorAll('#tActs button').length > 0, null, { timeout: 40000 }); });
  await step('pick starter', async () => { await p.click('#tActs button'); await p.waitForTimeout(900); await p.evaluate(() => document.getElementById('toast').classList.remove('show')); await p.evaluate(() => setSim(true)); });
  await step('scan and battle a wild to the end', async () => { await p.click('#scan'); await p.waitForTimeout(500);
    for (let i = 0; i < 60; i++) { const labels = await p.$$eval('#tActs button', bs => bs.map(x => x.textContent)); if (!labels.length) break; const idx = labels.findIndex(l => /Strike|Jab|Blow|Unleash/.test(l)); if (idx < 0) { await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, 0); await p.waitForTimeout(120); break; } await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, idx); await p.waitForTimeout(90); } });
  await step('scan and throw a catch item', async () => { await p.evaluate(() => document.getElementById('toast').classList.remove('show')); await p.click('#scan'); await p.waitForTimeout(400);
    for (let i = 0; i < 30; i++) { const labels = await p.$$eval('#tActs button', bs => bs.map(x => x.textContent)); const j = labels.findIndex(l => /Pok|ball|Throw|I ×/i.test(l)); if (j >= 0) { await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, j); await p.waitForTimeout(250); break; } const k = labels.findIndex(l => /Strike|Jab/.test(l)); if (k < 0) break; await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, k); await p.waitForTimeout(90); }
    await p.evaluate(() => document.getElementById('toast').classList.remove('show')); });
  await step('fight a route trainer', async () => { const chip = await p.$('#trainersBar button'); if (!chip) return; await chip.click(); await p.waitForTimeout(300);
    for (let i = 0; i < 80; i++) { const labels = await p.$$eval('#tActs button', bs => bs.map(x => x.textContent)); if (!labels.length) break; const idx = labels.findIndex(l => /Strike|Jab|Blow|Unleash|Guard/.test(l)); if (idx < 0) { await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, 0); break; } await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, idx); await p.waitForTimeout(80); }
    await p.evaluate(() => document.getElementById('toast').classList.remove('show')); });
  await step('walk to a gym and fight the leader', async () => { await p.evaluate(() => { const d = describe(state.lat, state.lon); for (let i = -5; i <= 5; i++) for (let j = -5; j <= 5; j++) { const c = cellCenter(d.rx + i, d.ry + j); const dd = describe(c.lat, c.lon); if (dd.atGym) { moveTo(c.lat, c.lon, false); updateHud(); return; } } });
    await p.waitForTimeout(400); const g = await p.$('#gymBtn'); if (g && await g.isVisible()) { await g.click(); await p.waitForTimeout(300);
      for (let i = 0; i < 120; i++) { const labels = await p.$$eval('#tActs button', bs => bs.map(x => x.textContent)); if (!labels.length) break; const idx = labels.findIndex(l => /Strike|Jab|Blow|Unleash|Guard/.test(l)); if (idx < 0) { await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, 0); break; } await p.evaluate(i => { const b = [...document.querySelectorAll('#tActs button')][i]; if (b) b.click(); }, idx); await p.waitForTimeout(70); } }
    await p.evaluate(() => document.getElementById('toast').classList.remove('show')); });
  await step('team panel: all four tabs', async () => { await p.click('#team'); await p.waitForTimeout(300); for (const t of ['team','collection','progress','world']) { await p.click('#pTabs button[data-tab=' + t + ']'); await p.waitForTimeout(200); } });
  await step('team row: expand, nickname, pin, reorder, box', async () => { await p.click('#pTabs button[data-tab=team]'); await p.waitForTimeout(200); await p.click('#pTeam .mon .tog'); await p.waitForTimeout(200);
    const acts = await p.$$('#pTeam .mon .acts button'); const labels = await Promise.all(acts.map(x => x.textContent()));
    const pin = labels.findIndex(l => /Pin/.test(l)); if (pin >= 0) { await acts[pin].click(); await p.waitForTimeout(200); }
    await p.evaluate(() => { const m = state.save.team[0]; m.nick = 'Test'; persistSave(); renderTeam(); }); });
  await step('release a creature', async () => { await p.evaluate(() => { const sp = PACK.speciesById.get('0016pidg'); addMonster(state.save, makeMonster(state.save, { species: sp, level: 6 }, null)); persistSave(); renderTeam(); });
    await p.waitForTimeout(200); const togs = await p.$$('#pTeam .mon .tog'); if (togs.length > 1) { await togs[1].click(); await p.waitForTimeout(200); const rel = await p.$('#pTeam .mon:nth-child(2) .acts button:has-text("Release")'); if (rel) { await rel.click(); await p.waitForTimeout(400); } } });
  await step('dex', async () => { await p.click('#pTabs button[data-tab=collection]'); await p.waitForTimeout(200); await p.click('#dexBtn'); await p.waitForTimeout(600); const back = await p.$('#panel button:has-text("Back")'); if (back) await back.click(); await p.waitForTimeout(200); });
  await step('team photo open and close', async () => { await p.click('#pTabs button[data-tab=team]'); await p.waitForTimeout(150); await p.click('#photoBtn'); await p.waitForTimeout(700); await p.click('#photoClose'); await p.waitForTimeout(200); });
  await step('weekly report share line', async () => { await p.click('#pTabs button[data-tab=progress]'); await p.waitForTimeout(300); const sh = await p.$('#weekShare'); if (sh) await sh.click(); await p.waitForTimeout(200); await p.click('#panelClose'); });
  await step('shop: buy and heal', async () => { await p.evaluate(() => { panel.classList.remove('show'); menu.classList.remove('show'); }); await p.click('#shopBtn'); await p.waitForTimeout(400); const buy = await p.$('#shop button:has-text("Buy")'); if (buy) { await buy.click(); await p.waitForTimeout(250); } await p.click('#shopClose'); await p.waitForTimeout(150);
    await p.evaluate(() => { document.getElementById('shop').classList.remove('show'); panel.classList.add('show'); renderTeam(); }); await p.waitForTimeout(250); await p.click('#heal'); await p.waitForTimeout(300); await p.click('#panelClose'); });
  await step('online sheet: register and all four tabs', async () => { await p.click('#onlineBtn'); await p.waitForTimeout(300); const h = await p.$('#mpHandle'); if (h) { await p.fill('#mpHandle', 'Casim'); await p.click('#mpReg'); await p.waitForTimeout(600); }
    for (const t of ['you','friends','battle','trade']) { await p.click('#oTabs button[data-tab=' + t + ']'); await p.waitForTimeout(250); }
    await p.click('#oTabs button[data-tab=you]'); await p.waitForTimeout(200); const ach = await p.$('.achBtn'); if (ach) { await ach.click(); await p.waitForTimeout(150); } await p.click('#mpClose'); });
  await step('directions: search, modes, voice, whole route, clear', async () => { await p.click('#guideBtn'); await p.waitForTimeout(400);
    await p.fill('#tActs input', 'Kitchener Market'); await p.keyboard.press('Enter'); await p.waitForTimeout(600);
    const geo = await p.$('#tActs .geo'); if (geo) await geo.click(); else { const first = await p.$('#tActs button:has-text("gym")'); if (first) await first.click(); }
    await p.waitForTimeout(1500); await p.click('#navMore'); await p.waitForTimeout(200);
    for (const m of ['bike','car','walk']) { await p.click('#navModes button[data-mode=' + m + ']'); await p.waitForTimeout(700); }
    await p.click('#navVoice'); await p.waitForTimeout(300); await p.click('#navWhole'); await p.waitForTimeout(600); await p.click('#centerBtn'); await p.waitForTimeout(400); await p.click('#navClose'); await p.waitForTimeout(300); });
  await step('menu: every tab and the toggles that change the world', async () => { await p.evaluate(() => { panel.classList.remove('show'); menu.classList.add('show'); }); await p.waitForTimeout(300);
    for (const t of ['play','world','places','data','help']) { await p.click('#mTabs button[data-tab=' + t + ']'); await p.waitForTimeout(200); }
    await p.click('#mTabs button[data-tab=play]'); for (const id of ['wakeBtn','lowPower','handicap','roam','routeVoiceBtn','voiceBtn','sfxBtn','notify']) { const el = await p.$('#' + id); if (el) { await el.click(); await p.waitForTimeout(150); } }
    for (const id of ['wakeBtn','lowPower']) { const el = await p.$('#' + id); if (el) { await el.click(); await p.waitForTimeout(150); } }
    await p.click('#mTabs button[data-tab=world]'); await p.waitForTimeout(150);
    for (const id of ['viewMode','squares','migration','neighbours','viewMode']) { const el = await p.$('#' + id); if (el) { await el.click(); await p.waitForTimeout(400); } }
    await p.evaluate(() => menu.classList.remove('show')); await p.waitForTimeout(200); });
  await step('grid view and region view', async () => { await p.evaluate(() => { panel.classList.remove('show'); menu.classList.add('show'); });  await p.click('#mTabs button[data-tab=world]'); await p.click('#viewMode'); await p.waitForTimeout(600); await p.evaluate(() => menu.classList.remove('show')); await p.waitForTimeout(300); await p.click('#viewBtn'); await p.waitForTimeout(600); await p.click('#viewBtn'); await p.waitForTimeout(500); await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=world]'); await p.click('#viewMode'); await p.waitForTimeout(500); await p.evaluate(() => menu.classList.remove('show')); });
  await step('region details: all six tabs', async () => { await p.evaluate(() => { menu.classList.remove('show'); panel.classList.add('show'); renderTeam(); }); await p.waitForTimeout(250); await p.click('#pTabs button[data-tab=world]'); await p.waitForTimeout(250); const r = await p.$('#pRegions .mon button:has-text("Details")'); if (r) { await r.click(); await p.waitForTimeout(500); for (const t of ['overview','gyms','week','legends','about','history']) { const b2 = await p.$('#rTabs button[data-tab=' + t + ']'); if (b2) { await b2.click(); await p.waitForTimeout(200); } } const back = await p.$('#panel button:has-text("Back")'); if (back) await back.click(); } await p.click('#panelClose'); });
  await step('guide: every topic', async () => { await p.evaluate(() => { panel.classList.remove('show'); menu.classList.add('show'); }); await p.click('#mTabs button[data-tab=help]'); await p.click('#guideOpen'); await p.waitForTimeout(300);
    const ids = await p.$$eval('#guideTopic option', os => os.map(o => o.value)); for (const id of ids) { await p.selectOption('#guideTopic', id); await p.waitForTimeout(120); } await p.click('#guideClose'); });
  await step('switch playthrough slots and come back', async () => { await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=world]'); await p.click('#layout'); await p.waitForTimeout(1400); await p.evaluate(() => document.getElementById('toast').classList.remove('show'));
    await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=world]'); await p.click('#routeSize'); await p.waitForTimeout(1400); await p.evaluate(() => document.getElementById('toast').classList.remove('show'));
    await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=world]'); await p.click('#routeSize'); await p.waitForTimeout(1300); await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=world]'); await p.click('#layout'); await p.waitForTimeout(1300); await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=world]'); await p.click('#layout'); await p.waitForTimeout(1600); await p.evaluate(() => document.getElementById('toast').classList.remove('show')); });
  await step('export and import the save', async () => { await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=data]'); await p.waitForTimeout(200); const dl = p.waitForEvent('download', { timeout: 6000 }).catch(() => null); await p.click('#exportSave'); const d = await dl; if (d) { const path = await d.path(); if (path) { await p.setInputFiles('#saveFile', path); await p.waitForTimeout(700); } } });
  await step('reset one part only', async () => { await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=data]'); await p.click('#reset'); await p.waitForTimeout(400); const row = await p.$('#resetList .resetRow:has-text("Bag")'); if (row) await row.click(); const go = await p.$('#tActs button:has-text("Reset the ticked")'); if (go) { await go.click(); await p.waitForTimeout(600); } await p.evaluate(() => document.getElementById('toast').classList.remove('show')); });
  await step('connection check and offline tiles', async () => { await p.evaluate(() => menu.classList.add('show')); await p.click('#mTabs button[data-tab=places]'); await p.waitForTimeout(200); await p.click('#netCheck'); await p.waitForTimeout(1200); await p.click('#tileClear'); await p.waitForTimeout(400); await p.evaluate(() => menu.classList.add('show')); await p.click('#pinAdd'); await p.waitForTimeout(300); const opt = await p.$('#tActs button'); if (opt) await opt.click(); await p.waitForTimeout(300); await p.evaluate(() => menu.classList.remove('show')); });
  await step('reload and confirm the save came back', async () => { await p.reload(); await p.waitForTimeout(4000); });
  const final = await p.evaluate(() => ({ team: state.save.team.length, coins: state.save.coins, badges: badgeCount(state.save), pack: PACK.meta.name, route: describe(state.lat, state.lon).routeNo }));
  require('fs').writeFileSync('/home/claude/sweep-out.json', JSON.stringify({ steps, problems, final }, null, 1)); await b.close();
})().catch(e => { require('fs').writeFileSync('/home/claude/sweep-out.json', JSON.stringify({ steps, problems: problems.concat('HARNESS: ' + e.message), final: null }, null, 1)); process.exit(0); });
